call plug#begin()
  Plug 'ap/vim-css-color'
  Plug 'tpope/vim-commentary'
call plug#end()

let mapleader = " "
set number
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4
set mouse=a
set dir=~/.cache/vim
set clipboard=unnamedplus
set viminfo=
set backspace=indent,eol,start
set wildmenu

nnoremap <silent> <leader>h :nohlsearch<CR>

nnoremap d "_d
vnoremap d "_d
