call plug#begin()
    Plug 'tpope/vim-commentary'
    Plug 'sheerun/vim-polyglot'
call plug#end()

colors default
let mapleader = ' '
set number
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4
set mouse=a
set dir=~/.cache/vim
set clipboard=unnamedplus
set viminfo=
set backspace=indent,eol,start
set wildmenu

nnoremap <silent> <leader>h :nohlsearch<CR>
