require("config.nvim-tree")
require("config.bufferline")
require("config.debug")
require("config.lint")
require("config.color")
require("config.noice")
require("config.treesitter")
-- require("config.lspconfig")
-- require("config.completions")
