require("config.lualine")
require("config.nvim-tree")
require("config.treesitter")
require("config.bufferline")
require("config.debug")
require("config.lint")
-- require("config.lspconfig")
-- require("config.completions")
