[config_selecte]
delay = 0
save_path = "/home/uniq/Pictures/Screenshots/"
file_name = "Screenshot- + year + - + month + - + day + - + hour + : + minute + : + second"
save_type = "png"

[config_window]
delay = 0
save_path = "/home/uniq/Pictures/Screenshots/"
file_name = "Screenshot- + year + - + month + - + day + - + hour + : + minute + : + second"
save_type = "png"

[config_fulshot]
delay = 0
save_path = "/home/uniq/Pictures/Screenshots/"
file_name = "Screenshot- + year + - + month + - + day + - + hour + : + minute + : + second"
save_type = "png"
